### ISSUE TITLE
about keypair_update

### ISSUE THREAD

**Issue by Cjyoleon** [smartalock/wireguard-lwip#6]

**Comment by inorick** [comment]
I think the `keypair_update` function rotates the keys (`prev` <- `curr` <- `next`) if the `next` key pair has been acknowledged, i.e. if `key_is_next` in line 454 is true:
https://github.com/smartalock/wireguard-lwip/blob/0c44df308984abfb9c9df628002cdf8154c55506/src/wireguard.c#L454

So the rotation looks good to me:

1. Overwrite `prev` with `curr`.
2. Overwrite `curr` with `next`.
3. Destroy `next` as it has been rotated to `curr`.
